### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by doxiaodong** [piglei/django-qiniu#3]
![image](https://cloud.githubusercontent.com/assets/6927481/9710487/9d9e2428-556d-11e5-9dce-40b0be069f9e.png)

在使用 QiNiuImageField 出现这样正常么？
```pyhton
def qiniu_key_maker_image(instance, filename):
    pass
```
还有这里怎么写呢

**Comment by piglei** [comment]
@doxiaodong 第一个截图是Django Admin里面的吗？应该是正常的，这个Field没有针对admin系统编写适配代码。

第二个问题，upload_to函数的主要功能是返回一个有效且不重复的文件名，一般情况下会根据instance和filename参数的值计算md5之类用来当文件名，不过具体还是看你自己的需求。

一个最简单的例子：

```python
def qiniu_key_maker_image(instance, filename):
    # 每一次都返回同一个文件名
    return 'test.jpg'
```

**Comment by doxiaodong** [comment]
谢谢～
